### ISSUE TITLE
Error: Cannot find module 'C:\dev\projets\wordpress\install.js'

### ISSUE THREAD

**Issue by neovea** [Huddle/PhantomCSS#119]
Hello, I just tried to install PhantomCSS with no luke.
I tried uninstalling and installing nodeJS again, but still the same error.

```
$ npm install phantomcss
\
> phantomjs@1.9.7-14 install C:\dev\projets\wordpress\node_modules\phantomcss\no
de_modules\phantomjs
> node install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\dev\projets\wordpress\install.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
-
> phantomjs@1.9.17 install C:\dev\projets\wordpress\node_modules\phantomcss\node
_modules\casperjs\node_modules\phantomjs
> node install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\dev\projets\wordpress\install.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "phantomcss"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.7-14 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.7-14 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\projets\wordpress\npm-debug.log
```

Thanks for helping

**Comment by jamescryer** [comment]
Hard to say from that error, looks to be failing on the PhantomJS install.  Let us know if you've figured it out.
